---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager-mixin-rules
  labels:
    k8s-app: prometheus
    prometheus: k8s
    role: alert-rules
spec:
  groups: []
