groups:
- name: GrafanaAlerts
  rules:
  - alert: GrafanaRequestsFailing
    annotations:
      message: '''{{ $labels.namespace }}'' / ''{{ $labels.job }}'' / ''{{ $labels.handler
        }}'' is experiencing {{ $value | humanize }}% errors'
    expr: |
      100 * namespace_job_handler_statuscode:http_request_total:rate5m{handler!~"/datasources/proxy/:id.*|/ds/query|/tsdb/query", statuscode=~"5.."}
      /
      namespace_job_handler_statuscode:http_request_total:rate5m{handler!~"/datasources/proxy/:id.*|/ds/query|/tsdb/query"}
      > 0.5
    for: 5m
    labels:
      severity: warning
