# labels to be used with /area command
area:
  - 'kubernetes'

kind:
  - 'documentation'
  - 'discussion'
  - 'feature'
  - 'question'

priority:
  - 'low'
  - 'medium'
  - 'high'
  - 'critical'

# File globs for PR labeler
# tests:
#   - '**/*.test.ts'
