name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
# https://gitmoji.carloscuesta.me/
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'kind/feature'
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🚨 Maintenance'
    labels:
      - 'area/renovate'
      - 'chore'
  - title: '📝 Documentation'
    labels:
      - 'kind/documentation'
  - title: '💡 Question'
    labels:
      - 'kind/question'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 🚧 Changes

  $CHANGES
