# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      args:
      - '--allow-multiple-documents'
      exclude: mkdocs.yml
    - id: check-added-large-files
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
  - id: insert-license
    stages: [commit]
    files: (Makefile|\.mk|\.yaml|\.yml|\.toml)
    exclude: ^\.secrets/.*$|^\.git-crypt/.*$
    args:
    - --license-filepath
    - LICENSE
    - --remove-header
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
  - id: insert-license
    stages: [commit]
    files: (\.libsonnet)
    exclude: ^\.secrets/.*$|^\.git-crypt/.*$
    args:
    - --license-filepath
    - LICENSE
    - --comment-style
    - '//'
    - --remove-header
- repo: https://github.com/waisbrot/pre-commit-jsonnet.git
  rev: v1.0
  hooks:
    - id: jsonnetfmt
