{
 "title": "Cilium / Components / Conntrack",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [ "cilium-agent" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Conntrack GC Run Rate by Status",
   "type": "timeseries",
   "description": "Rate at which ConnTrack reported its run outcome. Runs reported \"uncompleted\" may indicate a problem with ConnTrack GC, which could lead to full CT tables and dropped packets.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_datapath_conntrack_gc_runs_total{pod=~\"$pod\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Conntrack GC Key Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Entries" } },
   "targets": [
    {
     "expr": "topk($k, sum(cilium_datapath_conntrack_gc_entries{pod=~\"$pod\"}) by (pod, status))",
     "legendFormat": "{{pod}} {{status}}"
    }
   ]
  },
  {
   "title": "Total Conntrack GC Key Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Entries" } },
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_gc_entries{pod=~\"$pod\"}) by (status)",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Conntrack GC Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "quantile(0.95, sum(rate(cilium_datapath_conntrack_gc_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_datapath_conntrack_gc_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.5, sum(rate(cilium_datapath_conntrack_gc_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_datapath_conntrack_gc_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "P50"
    },
    {
     "expr": "quantile(0.25, sum(rate(cilium_datapath_conntrack_gc_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_datapath_conntrack_gc_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "P25"
    }
   ]
  },
  {
   "title": "Conntrack GC Key Fallbacks",
   "type": "timeseries",
   "description": "Rate at which ConnTrack reported its run outcome. Runs reported \"uncompleted\" may indicate a problem with ConnTrack GC, which could lead to full CT tables and dropped packets.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_datapath_conntrack_gc_key_fallbacks_total{pod=~\"$pod\"}[$__rate_interval])) by (family, protocol)",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Top Agent Conntrack GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_datapath_conntrack_gc_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_datapath_conntrack_gc_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack GC Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Entries" } },
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (status, family)",
     "legendFormat": "{{family}} {{status}}"
    }
   ]
  }
 ]
}