---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: linkerd-edge-mixin-alerts
  labels:
    app: prometheus
spec:
  groups:
  - name: linkerd
    rules:
    - alert: LinkerdRequestsHighErrorRate
      annotations:
        message: Linkerd error rate for {{ $labels.deployment | $labels.statefulset
          | $labels.daemonset }}.
        runbook_url: https://github.com/nlamiraut/monitoring-mixins/tree/master/mixins/linkerd-edge-mixin/runbook.md#alert-name-linkerdrequestshigherrorrate
        summary: Linkerd have high error rate for more than 10 minutes.
      expr: sum(rate(request_errors_total[1m])) by (deployment, statefulset, daemonset)
        / sum(rate(request_total[1m])) by (deployment, statefulset, daemonset) * 100
        > 10
      for: 10m
      labels:
        severity: warning
