groups:
- name: grafana_rules
  rules:
  - expr: |
      sum by (namespace, job, handler, statuscode) (rate(http_request_total[5m]))
    record: namespace_job_handler_statuscode:http_request_total:rate5m
