{
 "title": "Mesh and Envoy Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "osm_controller_instance",
    "label": "OSM Controller instance",
    "query": "label_values(osm_proxy_connect_count, source_pod_name)"
   },
   {
    "name": "osm_injector_instance",
    "label": "OSM Injector instance",
    "query": "label_values(osm_injector_injector_sidecar_count, source_pod_name)"
   },
   {
    "name": "xds_path",
    "label": "xDS Path",
    "query": "label_values(osm_proxy_config_update_time_bucket, resource_type)"
   }
  ]
 },
 "panels": [
  { "title": "Mesh Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitored Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "osm_k8s_monitored_namespace_count{source_pod_name=~\"$osm_controller_instance\"}",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Services in the Mesh",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(osm_k8s_api_event_count{type=\"service-added\", source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name) OR on() vector(0) - sum(osm_k8s_api_event_count{type=\"service-deleted\", source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name) OR on() vector(0)",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(osm_k8s_api_event_count{type=\"pod-added\", source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name) OR on() vector(0) - sum(osm_k8s_api_event_count{type=\"pod-deleted\", source_pod_name=~\"$osm_controller_instance\"}) by (source_pod_name) OR on() vector(0)",
     "legendFormat": "{{source_pod_name}}"
    }
   ]
  },
  {
   "title": "Connected Proxies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "osm_proxy_connect_count{source_pod_name=~\"$osm_controller_instance\"}",
     "legendFormat": "Connected proxies"
    }
   ]
  },
  {
   "title": "Control plane resource consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "CPU%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"osm-system\", container!~\"POD\", container!~\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory footprint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"osm-system\", container!=\"\", container!=\"POD\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "OSM Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Sidecar injector timings (sec)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "idelta(osm_injector_injector_rq_time_bucket{source_pod_name=~\"$osm_injector_instance\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Certificate Issue timings (sec)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "sum(idelta(osm_cert_issued_time_bucket{source_pod_name=~\"$osm_injector_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "xDS Path histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(idelta(osm_proxy_config_update_time_bucket{resource_type=\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Injector Webhooks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "idelta(osm_injector_injector_rq_time_count{success=\"true\", source_pod_name=~\"$osm_injector_instance\"}[1m])\n",
     "legendFormat": "Success"
    },
    {
     "expr": "idelta(osm_injector_injector_rq_time_count{success=\"false\", source_pod_name=~\"$osm_injector_instance\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "xDS Updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "idelta(osm_proxy_config_update_time_count{success=\"true\", resource_type=~\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1m])\n",
     "legendFormat": "{{resource_type}}-{{source_pod_name}}-Success"
    },
    {
     "expr": "idelta(osm_proxy_config_update_time_count{success=\"false\", resource_type=~\"$xds_path\", source_pod_name=~\"$osm_controller_instance\"}[1m])",
     "legendFormat": "{{resource_type}}-{{source_pod_name}}-Failure"
    }
   ]
  }
 ]
}