{
 "title": "ClickHouse latency",
 "tags": [ "clickhouse-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ClickHouseProfileEvents_DiskReadElapsedMicroseconds,job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(ClickHouseProfileEvents_DiskReadElapsedMicroseconds{job=~\"$job\"}, instance)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ClickHouseProfileEvents_DiskReadElapsedMicroseconds{job=~\"$job\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk read latency",
   "type": "timeseries",
   "description": "Time spent waiting for read syscall",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_DiskReadElapsedMicroseconds{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval)",
     "legendFormat": "{{ instance }} - disk read elapsed"
    }
   ]
  },
  {
   "title": "Disk write latency",
   "type": "timeseries",
   "description": "Time spent waiting for write syscall",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_DiskWriteElapsedMicroseconds{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval)",
     "legendFormat": "{{ instance }} - disk write elapsed"
    }
   ]
  },
  {
   "title": "Network receive latency",
   "type": "timeseries",
   "description": "Latency of inbound network traffic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_NetworkReceiveElapsedMicroseconds{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval)",
     "legendFormat": "{{ instance }} - network receive elapsed"
    }
   ]
  },
  {
   "title": "Network transmit latency",
   "type": "timeseries",
   "description": "Latency of outbound network traffic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_NetworkSendElapsedMicroseconds{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval)",
     "legendFormat": "{{ instance }} - network send elapsed"
    }
   ]
  },
  {
   "title": "ZooKeeper wait time",
   "type": "timeseries",
   "description": "Time spent waiting for ZooKeeper request to process",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_ZooKeeperWaitMicroseconds{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval)",
     "legendFormat": "{{ instance }} - ZooKeeper wait"
    }
   ]
  }
 ]
}