{
 "title": "ClickHouse replica",
 "tags": [ "clickhouse-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ClickHouseMetrics_InterserverConnection,job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"$job\"}, instance)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"$job\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Interserver connections",
   "type": "timeseries",
   "description": "Number of connections due to interserver communication",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_InterserverConnection{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - interserver connections"
    }
   ]
  },
  {
   "title": "Replica queue size",
   "type": "timeseries",
   "description": "Number of replica tasks in queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxQueueSize{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max queue size"
    }
   ]
  },
  {
   "title": "Replica operations",
   "type": "timeseries",
   "description": "Replica Operations over time to other nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetches{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - part fetches"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - part merges"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMutations{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - part mutations"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartChecks{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - part checks"
    }
   ]
  },
  {
   "title": "Replica read only",
   "type": "timeseries",
   "description": "Shows replicas in read-only state over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - read only"
    }
   ]
  },
  {
   "title": "Zookeeper watches",
   "type": "timeseries",
   "description": "Current number of watches in ZooKeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperWatch{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - ZooKeeper watch"
    }
   ]
  },
  {
   "title": "Zookeeper sessions",
   "type": "timeseries",
   "description": "Current number of sessions to ZooKeeper",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperSession{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - ZooKeeper session"
    }
   ]
  },
  {
   "title": "Zookeeper requests",
   "type": "timeseries",
   "description": "Current number of active requests to ZooKeeper",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperRequest{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - ZooKeeper request"
    }
   ]
  }
 ]
}