{
 "title": "ksqldb Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "clusterid",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,ksql_cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_active_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "stat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_running_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Persisted Queries",
   "type": "stat",
   "description": "Num of persisted queries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_persistent_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "stat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries in Error State",
   "type": "stat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Idle Queries",
   "type": "stat",
   "description": "Num of idle queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_idle_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ksql_ksql_metrics_ksql_queries_query_status{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Stopped Queries",
   "type": "stat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Currently Shutting Down Queries",
   "type": "stat",
   "description": "Num of running queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_pending_shutdown_queries{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster liveness",
   "type": "graph",
   "description": "Cluster liveness",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_liveness_indicator{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message consumed/sec",
   "type": "graph",
   "description": "Message consumed/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_consumed_per_sec{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message produced/sec",
   "type": "graph",
   "description": "Message produced/sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ksql_ksql_engine_query_stats_messages_produced_per_sec{job=\"integrations/kafka-ksqldb\",  ksql_cluster=\"$clusterid\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"integrations/kafka-ksqldb\",  instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"integrations/kafka-ksqldb\", instance=~\"$instance\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"integrations/kafka-ksqldb\",area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"integrations/kafka-ksqldb\",  instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Poll Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Poll Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Process Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Process Latency Max",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_max{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Commit Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Commit Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  { "title": "StateStore Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Put Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_rate{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate_rate{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_fetch_rate{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_fetch_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_rate{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_rate{job=\"integrations/kafka-ksqldb\",  thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 100 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 100 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  }
 ]
}