---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: minio-mixin-alerts
  labels:
    app: prometheus
spec:
  groups:
  - name: minio
    rules:
    - alert: minioDisksOffline
      annotations:
        message: MinIO '{{ $labels.instance }}' has disks offline
      expr: |
        minio_disks_offline != 0
      for: 1m
      labels:
        severity: critical
    - alert: minioStorageUsed
      annotations:
        message: MinIO disk '{{ $labels.disk }}' has more than 80% storaged used
      expr: |
        disk_storage_used / disk_storage_total > 0.8
      for: 1m
      labels:
        severity: warning
