name: 'mixins'
description: 'A GitHub Action for generate monitoring mixins'
author: 'Nicolas Lamirault'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  version:
    description: "Application version"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VERSION: ${{ inputs.version }}
