# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sealed-secrets-mixin-alerts
  labels:
    app: prometheus
spec:
  groups:
  - name: sealed-secrets
    rules:
    - alert: SealedSecretsUnsealErrorHigh
      annotations:
        description: High number of errors during unsealing Sealed Secrets in {{ $labels.namespace
          }} namespace.
        runbook_url: https://github.com/bitnami-labs/sealed-secrets
        summary: Sealed Secrets Unseal Error High
      expr: |
        sum by (reason, namespace) (rate(sealed_secrets_controller_unseal_errors_total{}[5m])) > 0
      labels:
        severity: warning
