# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

groups:
    - name: Kafka_Alerts
      rules:
        - alert: KafkaOfflinePartitonCount
          annotations:
            description: Kafka cluster {{ $labels.kafka_cluster }} has {{ $value }} offline partitions. After successful leader election, if the leader for partition dies, then the partition moves to the OfflinePartition state. Offline partitions are not available for reading and writing. Restart the brokers, if needed, and check the logs for errors.
            summary: Kafka has offline partitons.
          expr: sum without(instance) (kafka_controller_kafkacontroller_offlinepartitionscount{job="integrations/kafka"}) > 0
          for: 5m
          labels:
            severity: critical
        - alert: KafkaUnderReplicatedPartitionCount
          annotations:
            description: Kafka instance {{ $labels.instance }} in cluster {{ $labels.kafka_cluster }} has {{ $value }} under replicated partitons
            summary: Kafka has under replicated partitons.
          expr: |
            sum without() (kafka_server_replicamanager_underreplicatedpartitions{job="integrations/kafka"}) > 0
          for: 5m
          labels:
            severity: critical
        - alert: KafkaActiveController
          annotations:
            description: Kafka cluster {{ $labels.kafka_cluster }} has {{ $value }} broker(s) reporting as the active controller in the last 5 minute interval. During steady state there should be only one active controller per cluster.
            summary: Kafka has no active controller.
          expr: sum without(instance) (kafka_controller_kafkacontroller_activecontrollercount{job="integrations/kafka"}) != 1
          for: 5m
          labels:
            severity: critical
        - alert: KafkaUncleanLeaderElection
          annotations:
            description: Kafka cluster {{ $labels.kafka_cluster }} has {{ $value }} unclean partition leader elections reported in the last 5 minute interval. When unclean leader election is held among out-of-sync replicas, there is a possibility of data loss if any messages were not synced prior to the loss of the former leader. So if the number of unclean elections is greater than 0, investigate broker logs to determine why leaders were re-elected, and look for WARN or ERROR messages. Consider setting the broker configuration parameter unclean.leader.election.enable to false so that a replica outside of the set of in-sync replicas is never elected leader.
            summary: Kafka has unclean leader elections.
          expr: max without(instance) (rate(kafka_controller_controllerstats_uncleanleaderelectionspersec{job="integrations/kafka"}[5m])) != 0
          for: 5m
          labels:
            severity: critical
        - alert: KafkaISRExpandRate
          annotations:
            description: Kafka instance {{ $labels.instance }} in cluster {{ $labels.kafka_cluster }} ISR is expanding by {{ $value }} per second. If a broker goes down, ISR for some of the partitions shrink. When that broker is up again, ISRs are expanded once the replicas are fully caught up. Other than that, the expected value for ISR expansion rate is 0. If ISR is expanding and shrinking frequently, adjust Allowed replica lag.
            summary: Kafka ISR Expansion Rate is expanding.
          expr: |
            sum without() (rate(kafka_server_replicamanager_isrexpandspersec{job="integrations/kafka"}[5m])) != 0
          for: 5m
          labels:
            severity: warning
        - alert: KafkaISRShrinkRate
          annotations:
            description: Kafka instance {{ $labels.instance }} in cluster {{ $labels.kafka_cluster }} ISR is shrinking by {{ $value }} per second. If a broker goes down, ISR for some of the partitions shrink. When that broker is up again, ISRs are expanded once the replicas are fully caught up. Other than that, the expected value for ISR shrink rate is 0. If ISR is expanding and shrinking frequently, adjust Allowed replica lag.
            summary: Kafka ISR Expansion Rate is shrinking.
          expr: |
            sum without() (rate(kafka_server_replicamanager_isrshrinkspersec{job="integrations/kafka"}[5m])) != 0
          for: 5m
          labels:
            severity: warning
        - alert: KafkaBrokerCount
          annotations:
            description: Kafka cluster {{ $labels.kafka_cluster }} broker count is 0.
            summary: Kafka has no Brokers online.
          expr: count without(instance) (kafka_server_kafkaserver_brokerstate{job="integrations/kafka"}) == 0
          for: 5m
          labels:
            severity: critical
        - alert: KafkaZookeeperSyncConnect
          annotations:
            description: Kafka instance {{ $labels.instance }} in cluster {{ $labels.kafka_cluster }} Zookeeper Sync Disconected.
            summary: Kafka Zookeeper Sync Disconected.
          expr: |
            avg without() (kafka_server_sessionexpirelistener_zookeepersyncconnectspersec{job="integrations/kafka"}) < 0
          for: 5m
          labels:
            severity: warning
