{
 "title": "Apollo Server",
 "description": "Monitor an application built using Apollo Server",
 "tags": [
  "node.js",
  "express",
  "apollo-server",
  "nodejs",
  "apollo"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(apollo_server_starting, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(apollo_server_starting, instance)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(apollo_server_starting, hostname)"
   },
   {
    "name": "requestTarget",
    "label": "Request Target",
    "query": "0.001,0.005,0.015,0.05,0.1,0.2,0.3,0.4,0.5,1,5,10"
   },
   {
    "name": "requestTolerance",
    "label": "Request Tolerance",
    "query": "0.001,0.005,0.015,0.05,0.1,0.2,0.3,0.4,0.5,1,5,10"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apdex Score",
   "type": "singlestat",
   "description": "Apdex score calculated using the selected request target and request tolerance.\n\nFor more information, please visit https://en.wikipedia.org/wiki/Apdex.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", le=\"$requestTarget\", success=\"true\"}) + (sum(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", le=\"$requestTolerance\", success=\"true\"}) - sum(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", le=\"$requestTarget\", success=\"true\"})) / 2) / sum(apollo_query_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", success=\"true\"})) * 100",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "singlestat",
   "description": "Requests per second for the selected interval.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "singlestat",
   "description": "Number of received requests.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"})",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Requests Error Rate",
   "type": "singlestat",
   "description": "The percentage of requests that errored.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"} OR on() vector(0)) / sum(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"})) * 100",
     "legendFormat": "Failed %"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "singlestat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  {
   "title": "Apollo Server Restarts",
   "type": "singlestat",
   "description": "The number of times Apollo Server restarted.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(apollo_server_starting{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range]))",
     "legendFormat": "Apollo Server"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "nodejs_version_info" }
   ]
  },
  {
   "title": "Apollo Server Version",
   "type": "singlestat",
   "description": "The version of Apollo Server.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "apollo_server_starting" }
   ]
  },
  { "title": "Apollo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "description": "Requests per second for the selected interval.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval])) by (instance, hostname)",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "description": "Errors per second for the selected interval.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval])) by (instance, hostname)",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "graph",
   "description": "Response latency for the selected interval.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apollo_query_duration_bucket{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval])) by (instance, hostname, le))",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apollo_query_duration_bucket{job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top 10 Operations Count",
   "type": "table",
   "description": "Top 10 most requested operations.\n\nN/A represents unnamed operations.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum (apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}) by (operationName))"
    }
   ]
  },
  {
   "title": "Top 10 Errors Count",
   "type": "table",
   "description": "Top 10 operations that errored.\n\nN/A represents unnamed operations.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum (apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}) by (operationName))"
    }
   ]
  },
  {
   "title": "Top 10 Duration Rate",
   "type": "table",
   "description": "Top 10 slowest operations.\n\nN/A represents unnamed operations.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apollo_query_duration_sum{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range])) by (operationName) / sum(rate(apollo_query_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range])) by (operationName))"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Fields Resolution",
   "type": "table",
   "description": "Top 10 fields with the slowest resolutions.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apollo_query_field_resolution_duration_sum{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", parentType!=\"Query\", parentType!=\"Mutation\"}[$__range])) by (fieldName, parentType) / sum(rate(apollo_query_field_resolution_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", parentType!=\"Query\", parentType!=\"Mutation\"}[$__range])) by (fieldName, parentType))"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "User CPU - {{instance}} - {{hostname}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "System CPU - {{instance}} - {{hostname}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "Total CPU - {{instance}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "Process Memory - {{instance}} - {{hostname}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "Heap Total - {{instance}} - {{hostname}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "Heap Used - {{instance}} - {{hostname}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}",
     "legendFormat": "External Memory - {{instance}} - {{hostname}}"
    }
   ]
  }
 ]
}