groups:
- name: memcached
  rules:
  - alert: MemcachedDown
    annotations:
      message: |
        Memcached Instance {{ $labels.job }} / {{ $labels.instance }} is down for more than 15mins.
    expr: |
      memcached_up == 0
    for: 15m
    labels:
      severity: critical
  - alert: MemcachedConnectionLimitApproaching
    annotations:
      message: |
        Memcached Instance {{ $labels.job }} / {{ $labels.instance }} connection usage is at {{ printf "%0.0f" $value }}% for at least 15m.
    expr: |
      (memcached_current_connections / memcached_max_connections * 100) > 80
    for: 15m
    labels:
      severity: warning
  - alert: MemcachedConnectionLimitApproaching
    annotations:
      message: |
        Memcached Instance {{ $labels.job }} / {{ $labels.instance }} connection usage is at {{ printf "%0.0f" $value }}% for at least 15m.
    expr: |
      (memcached_current_connections / memcached_max_connections * 100) > 95
    for: 15m
    labels:
      severity: critical
