---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: grafana-mixin-rules
  labels:
    app: prometheus
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: grafana_rules
    rules:
    - expr: |
        sum by (namespace, job, handler, statuscode) (rate(http_request_total[5m]))
      record: namespace_job_handler_statuscode:http_request_total:rate5m
