# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"
# on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with:
          charts_repo_url: https://charts.portefaix.xyz
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # Update the generated timestamp in the index.yaml
  # needed until https://github.com/helm/chart-releaser/issues/90
  # or helm/chart-releaser-action supports this
  post-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit and push timestamp updates
        run: |
          if [[ -f index.yaml ]]; then
            export generated_date=$(date --utc +%FT%T.%9NZ)
            sed -i -e "s/^generated:.*/generated: \"$generated_date\"/" index.yaml
            git add index.yaml
            git commit -sm "Update generated timestamp [ci-skip]" || exit 0
            git push
          fi

  update-website:
    needs: post-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npx js-yaml index.yaml | npx hbs-cli .github/templates/index.hbs -i - -e md
      
      - name: Commit and push website
        run: |
          git add index.md
          git commit -sm "Update website [ci-skip]" || exit 0
          git push