# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Lint and Test Charts

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"
  pull_request:
    branches:
      - master
    paths:
      - "charts/**"

# jobs:
#   lint-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Helm
#         uses: azure/setup-helm@v1
#         with:
#           version: v3.4.0

#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.7

#       - name: Set up chart-testing
#         uses: helm/chart-testing-action@v2.0.1

#       - name: Run chart-testing (lint)
#         id: lint
#         run: ct lint --config .github/ct.yaml
#         if: steps.list-changed.outputs.changed == 'true'

#       - name: Create kind cluster
#         uses: helm/kind-action@v1.1.0
#         if: steps.list-changed.outputs.changed == 'true'

#       - name: Run chart-testing (install)
#         run: ct install --config .github/ct.yaml
#         if: steps.list-changed.outputs.changed == 'true'



jobs:
  # Reference https://github.com/marketplace/actions/helm-chart-testing
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: lint
          config: .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run helm-docs
        run: .github/helm-docs.sh

  # kubeval-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #   strategy:
  #     matrix:
  #       k8s:
  #         # from https://github.com/instrumenta/kubernetes-json-schema
  #         - v1.14.10
  #         - v1.15.7
  #         - v1.16.4
  #         - v1.17.4
  #         - v1.18.1
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.4
  #       with:
  #         fetch-depth: 0

  #     - name: Run kubeval
  #       env:
  #         KUBERNETES_VERSION: ${{ matrix.k8s }}
  #       run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      # - kubeval-chart
    strategy:
      matrix:
        k8s:
          # from https://hub.docker.com/r/kindest/node/tags
          - v1.16.15
          - v1.17.11
          - v1.18.8
          - v1.19.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.1.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      # - name: Run chart-testing (install)
      #   uses: helm/chart-testing-action@v1.1.0
      #   with:
      #     command: install
      #     config: .github/ct.yaml
