name: Mixins / Build

# on:
#   push:
#     # branches to consider in the event; optional, defaults to all
#     branches:
#       - master
#     paths:
#       - "mixins/**"
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5

      - name: Generate mixins
        uses: ./.github/actions/mixins
        with:
          version: 0.0.0
