name: Renovate / Dependencies

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  renovate-helmrelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 1

    # - name: Update Helm Releases
    #   run: |
    #     docker-compose run -T --rm builder bootstrap/renovate-helm-releases.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/pre-commit-auto-update
        delete-branch: true
        title: Auto-update pre-commit hooks
        signoff: true
        committer: "Nicolas Lamirault <nlamirault@users.noreply.github.com>"
        author: "Nicolas Lamirault <nlamirault@users.noreply.github.com>"
        commit-message: Auto-update pre-commit hooks
        body: |
          Signed-off-by: Nicolas Lamirault <nlamirault@users.noreply.github.com>
        labels: dependencies, merge
